version: '3'
services:


  db:
    image: postgres:latest
    ports:
      - 54321:5432
    volumes:
      - ./dblocal:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: censys-local
      POSTGRES_USER: censys
      POSTGRES_PASSWORD: censys

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/censys
    depends_on:
      - db


